export const constant = {
    API_LOGIN_LOAD: 'API_LOGIN_LOAD',
    API_LOGIN_SUCESS: 'API_LOGIN_SUCESS',
    API_LOGIN_ERROR: 'API_LOGIN_ERROR',
    API_LOGIN_FAIL: 'API_LOGIN_FAIL',
  
    API_SIGNUP_LOAD: 'API_SIGNUP_LOAD',
    API_SIGNUP_SUCESS: 'API_SIGNUP_SUCESS',
    API_SIGNUP_ERROR: 'API_SIGNUP_ERROR',
    API_SIGNUP_FAIL: 'API_SIGNUP_FAIL',
  
    API_RESET_LOAD: 'API_RESET_LOAD',
    API_RESET_SUCESS: 'API_RESET_SUCESS',
    API_RESET_ERROR: 'API_RESET_ERROR',
    API_RESET_FAIL: 'API_RESET_FAIL',
  
    API_OTP_LOAD: 'API_OTP_LOAD',
    API_OTP_SUCESS: 'API_OTP_SUCESS',
    API_OTP_ERROR: 'API_OTP_ERROR',
    API_OTP_FAIL: 'API_OTP_FAIL',
  
    API_EDIT_LOAD: 'API_EDIT_LOAD',
    API_EDIT_SUCESS: 'API_EDIT_SUCESS',
    API_EDIT_ERROR: 'API_EDIT_ERROR',
    API_EDIT_FAIL: 'API_EDIT_FAIL',
  
    EDIT_PROFILE_LOAD: 'EDIT_PROFILE_LOAD',
    EDIT_PROFILE_SUCCESS: 'EDIT_PROFILE_SUCCESS',
    EDIT_PROFILE_ERROR: 'EDIT_PROFILE_ERROR',
    EDIT_PROFILE_FAIL: 'EDIT_PROFILE_FAIL',
  
    //Set loader
    SET_LOADER: 'SET_LOADER',
  };
  